### PR TITLE
Stream Health Feedback System (arbab) 

### PR DESCRIPTION
**Pull request by arbabali**
a draft pull request for My Stream Feedback system feature

### CODE REVIEW

**Comment by gerazo** [comment]
Before we start: @arbabali did you write tests?  Or this is the reason why this PR is a draft one?
@NadineAziz Did we have any tests for the frontend before?

**Comment by NadineAziz** [comment]
We don'y have tests for the frontend because we decided to go e2e then it was just used there so no we don't have

**Comment by NadineAziz** [comment]
@arbabali Since they are too many files in the same PR and this resembles an Epic for me, please make sure that everything is working well and integrated together and we can merge it upon your confirmation

**Comment by arbabali** [comment]
@gerazo  Hi,

- I have written test cases for **server side** code ensuring the comparability of my feature and integration with before written code. and now i have added these changes from other branch to this.

- I have also changed the structure of test directory as it was only one directory for all tests (api end points tests) 
now there is  different directory for each category of tests. 
` "test:api": "mocha server/test/test_api/test.js --exit"`
`"test:utils": "mocha server/test/test_utils --exit"`
`"test": "mocha server/test --exit"`

- For e2e front-end tests, I have written a few tests in nightwatch.js  in branch  _**feedback_testing**_ checking  the basic layout correctly , However I am still facing errors with  automated log-in tests for Vue app , which is essential to check further my feature on front-end.

**Comment by arbabali** [comment]
> 

sure , and i would like to add as this branch include all of my work on feature that  i implemented so it would be better that it is given green signal from reviewers  and merged by myself (my account) .
Later in project it will be clear on master who wrote what , in-case of failures or errors or even further improvements on feature it will be helpful to author and project manager.

**Comment by arbabali** [comment]
> @arbabali Since they are too many files in the same PR and this resembles an Epic for me, please make sure that everything is working well and integrated together and we can merge it upon your confirmation

sure , and i would like to add as this branch include all of my work on feature that i implemented so it would be better that it is given green signal from reviewers and merged by myself (my account) .
Later in project it will be clear on master who wrote what , in-case of failures or errors or even further improvements on feature it will be helpful to author and project manager.

**Comment by gerazo** [comment]
@NadineAziz Ok. @Norticus36 will help with this side ofthe testing I guess. @arbabali Otherwise this PR looks nice and I agree with @NadineAziz that if you make sure, it was well integrated, it can be merged.

**Review by gerazo — APPROVED** [review]
I approve and @NadineAziz will put some basic CI stuff in, so you can test those which are already covered. Then it can be merged.

**Pull request merged**
